### ISSUE TITLE
Edit the image and the text to make it sense

### ISSUE THREAD

**Issue by TrNgTien** [kenpham4real/socialject_alpha_1#34]
@HTD2k1 Can you see the demo of @Chillisaucery  and I post the problem in messenger, I hope you can edit that, with some situation org will has the name like IU EMC - IU event management club, that's very long name so i hope u can deal that and image too <3
![120040407_2118828958260940_27249615769741677_n](https://user-images.githubusercontent.com/66483590/94103033-bc224e80-fe5d-11ea-881d-443d57605b17.png)

**Comment by kenpham4real** [comment]
@TrNgTien **Please add an image or demo for clarity**

**Comment by Chillisaucery** [comment]
Well it is UI stuff, we can handle that later. Hopefully so.

**Comment by kenpham4real** [comment]
**Will close this issue due to deprecated UI Component**
