### ISSUE TITLE
ProjectInfoPage organization section UI is not working properly

### ISSUE THREAD

**Issue by kenpham4real** [kenpham4real/socialject_alpha_1#38]
![image](https://user-images.githubusercontent.com/30412786/94163333-ea317e00-feb1-11ea-91c0-704684d3b7a8.png)

**It'd be proper if the alignment of the text represents precisely as designed in Figma** 

![image](https://user-images.githubusercontent.com/30412786/94163789-717ef180-feb2-11ea-87e2-1bf5a367e8ac.png)

**Comment by Chillisaucery** [comment]
Yea I ask Đạt's permission to change the UI. Butt wait I thought we said we put this UI stuff later... Either way, gonna fix that.
