### ISSUE TITLE
Can not use facebook authentication

### ISSUE THREAD

**Issue by TrNgTien** [kenpham4real/socialject_alpha_1#51]
**Problem:**
When I choose continue Facebook, I can not login with Facebook.

![120293986_790089458392313_7020485780110006050_n](https://user-images.githubusercontent.com/66483590/94781081-8ba95a00-03f3-11eb-9ed8-db7079621bf1.png)

**Comment by kenpham4real** [comment]
We already discussed this case. I'll close the issue
