### ISSUE TITLE
TypeError in AddActivityModal page

### ISSUE THREAD

**Issue by TrNgTien** [kenpham4real/socialject_alpha_1#54]
Plz fix that, becuz my task is depended on this screen

![Untitled](https://user-images.githubusercontent.com/66483590/94896934-d04af900-04b8-11eb-9b86-ae80e7ec2ea1.png)

**Comment by kenpham4real** [comment]
This issue has been resolved in the newest PR: 
Commit: https://github.com/kenpham4real/socialject_alpha_1/pull/58/commits/8591892a671b8979519244b2cd4975e1bfd6eb51
