### ISSUE TITLE
Need to fix when click on view project from profile of PPU, it's have a bug

### ISSUE THREAD

**Issue by TrNgTien** [kenpham4real/socialject_alpha_1#59]
![Untitled](https://user-images.githubusercontent.com/66483590/94984147-414ee700-0573-11eb-82aa-c9dfbd3369f2.png)
plz fix it, i think u should use div, the a has href then u use onclick props.history.push so it's conflicted
  @Chillisaucery

**Comment by TrNgTien** [comment]
when i click on 1 of them, i can not navigate and that make a bug like the pic above
![image](https://user-images.githubusercontent.com/66483590/94992737-29e51d80-05b6-11eb-8c54-20dbd1a0b37c.png)

**Comment by Chillisaucery** [comment]
I have fixed both in the most recent push. Please check if it works properly or not.

**Comment by TrNgTien** [comment]
ok the issue is solved. i will close the issue
