### ISSUE TITLE
PPU still have access to add activity of other projects that don't belong to that PPU

### ISSUE THREAD

**Issue by kenpham4real** [kenpham4real/socialject_alpha_1#60]
**1. Problem:**
I tried to sign in with a totally new account as a PPU. 
When visiting other projects (I've not created any projects), the ProjectInfoPage still show the **Add activity** button for me
![image](https://user-images.githubusercontent.com/30412786/95005710-31dca600-0626-11eb-9440-3880f0a4eef9.png)

**2. Solution:**
I **don't see any authorization** for **this** **component** in **ProjectInfoPage**, so adding more conditions would be the solution for this

**Comment by Chillisaucery** [comment]
Oh fuck totally forgot this in the UI authorization. So there is this button that I should authorise, is there anything else? I thought there was only the follow button and the form submission stuff

**Comment by Chillisaucery** [comment]
Resolved, please check it in the UI enhancement branch
