### ISSUE TITLE
UI -- Project cards in ProjectList (aka ChooseType) doesn't align properly 

### ISSUE THREAD

**Issue by kenpham4real** [kenpham4real/socialject_alpha_1#61]
![image](https://user-images.githubusercontent.com/30412786/95007750-6576fa80-063d-11eb-86b9-f72cfe8ef4cb.png)

**Comment by Chillisaucery** [comment]
What, it looks fucking good. Also fucking responsive,

**Comment by kenpham4real** [comment]
Please adjust them to align from the left to the right @Chillisaucery

**Comment by Chillisaucery** [comment]
If align them from left to right it would look horrible in other devices besides the web platform. Are you okay with that?
