### ISSUE TITLE
I have a bug when i click on 1 project

### ISSUE THREAD

**Issue by TrNgTien** [kenpham4real/socialject_alpha_1#62]
![image](https://user-images.githubusercontent.com/66483590/95010859-e42c6180-0656-11eb-807a-bb3eb448b1fe.png)
when i click on this it has a bug like this 
![image](https://user-images.githubusercontent.com/66483590/95010869-f7d7c800-0656-11eb-9022-735218108179.png)

**Comment by Chillisaucery** [comment]
Resolved right

**Comment by kenpham4real** [comment]
**Resolved with my latest commits**
