### ISSUE TITLE
considering the tags in projectInfo

### ISSUE THREAD

**Issue by TrNgTien** [kenpham4real/socialject_alpha_1#63]
![image](https://user-images.githubusercontent.com/66483590/95010978-7b91b480-0657-11eb-8f78-61c5b836464c.png)
shall we delete this or if we keep those, plz make them can navigate to some where!
@HTD2k1

**Comment by kenpham4real** [comment]
@TrNgTien @HTD2k1  Please work on the new UI component. This one is deprecated
