### ISSUE TITLE
Fix-bugs -- Can not render ProjectInfoPage after login

### ISSUE THREAD

**Issue by kenpham4real** [kenpham4real/socialject_alpha_1#71]
**1. Problem:**
![image](https://user-images.githubusercontent.com/30412786/95486869-c5fb9400-09bd-11eb-8dee-dd9c9eba4857.png)
**Meanwhile, at the deployed version, it works fine**

**Comment by TrNgTien** [comment]
This is codes of Long, so he will fix but, we are tired so may be Saturday maybe @kenpham4real

**Comment by kenpham4real** [comment]
This works fine in production. Please look at the branch: **ver-1.0**
