### ISSUE TITLE
Can't see any added id of user after login with Google

### ISSUE THREAD

**Issue by TrNgTien** [kenpham4real/socialject_alpha_1#72]
when users login with gg, i can't see  any new ID of user

**Comment by kenpham4real** [comment]
> when users login with gg, i can't see any new ID of user

Please specify the problem in details

**Comment by TrNgTien** [comment]
i mean when user login then natural case the id of that user will be added in Firebase, but i can't see it anywhere @kenpham4real

**Comment by kenpham4real** [comment]
Would love if you can provide some figures or demos @TrNgTien

**Comment by TrNgTien** [comment]
@kenpham4real  check slack

**Comment by kenpham4real** [comment]
> @kenpham4real  check slack
> 

Pls put the demo here @TrNgTien

**Comment by kenpham4real** [comment]
> @kenpham4real  check slack
> 

Pls put the demo here @TrNgTien
