### ISSUE TITLE
Functionality :  Add a project can not navigate to createPostModal

### ISSUE THREAD

**Issue by TrNgTien** [kenpham4real/socialject_alpha_1#73]
![image](https://user-images.githubusercontent.com/66483590/95545500-3d660d80-0a28-11eb-8512-3cc637dd493d.png)
when i click on button add a project i can not navigate to anywhere
![image](https://user-images.githubusercontent.com/66483590/95545542-5c649f80-0a28-11eb-909f-d4e067e99713.png)

**Comment by kenpham4real** [comment]
This issue is resolved with my latest commit. The production version is updated as well
