### ISSUE TITLE
Can not submit answer of the project form as a SPU

### ISSUE THREAD

**Issue by kenpham4real** [kenpham4real/socialject_alpha_1#76]
![image](https://user-images.githubusercontent.com/30412786/95593968-8774e080-0a74-11eb-8ebb-80e545c5a652.png)
This is what it logs out when I hit the **Submit** button. And there is no data sent to the database @TrNgTien

**Comment by TrNgTien** [comment]
ok i will check it later

**Comment by kenpham4real** [comment]
Resolve with the latest push to master
