### ISSUE TITLE
Can't render project

### ISSUE THREAD

**Issue by TrNgTien** [kenpham4real/socialject_alpha_1#77]
![image](https://user-images.githubusercontent.com/66483590/95642899-cf781f80-0ad5-11eb-9d82-2384c07d1be3.png)

When i choose a project, i took this error in code version, but deploy version is still ok

**Comment by kenpham4real** [comment]
What is the branch @TrNgTien ?

**Comment by TrNgTien** [comment]
ok when we check everything is ok so i close this issue
