### ISSUE TITLE
Fetch the orgAvatar into Held by... in projectSlide

### ISSUE THREAD

**Issue by TrNgTien** [kenpham4real/socialject_alpha_1#88]
The orgAvatar into Held by... in projectSlide must be exactly the avatar of the clb, organization held that project. Here is an example.
![image](https://user-images.githubusercontent.com/66483590/96139186-c8fc0480-0f28-11eb-8ffd-e266b4b7546a.png)
![image](https://user-images.githubusercontent.com/66483590/96139234-d7e2b700-0f28-11eb-96e2-610109be4ddb.png)
![image](https://user-images.githubusercontent.com/66483590/96139253-de712e80-0f28-11eb-9f30-8fb3b06288cd.png)

**Comment by kenpham4real** [comment]
Resolved with the latest commit
